version: "3"

networks:
  net0:
    driver: overlay

services:

  redpanda:
    image: 'docker.vectorized.io/vectorized/redpanda:v22.3.4'
    hostname: "redpanda.internal.net"
    command:
      - redpanda
      - start
      - '--set redpanda.enable_sasl=true'
      - '--set redpanda.superusers=["user"]'
      - '--smp'
      - '1'
      - '--reserve-memory'
      - 0M
      - '--overprovisioned'
      - '--node-id'
      - '0'
      - '--kafka-addr'
      - 'INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092'
      - '--advertise-kafka-addr'
      - 'INSIDE://redpanda.internal.net:29092,OUTSIDE://localhost:9092'
    networks:
      - net0
    ports:
      - '9092:9092'
      - '29092:29092'
      - '9644:9644'

  init-redpanda:
    image: "docker.vectorized.io/vectorized/redpanda:v22.3.4"
    networks:
      - net0
    deploy:
      restart_policy:
        condition: none
        max_attempts: 0
    depends_on:
      - redpanda
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      rpk topic create commands --brokers redpanda.internal.net:29092 --user user --password redpanda --sasl-mechanism SCRAM-SHA-256
      rpk topic create replies --brokers redpanda.internal.net:29092 --user user --password redpanda --sasl-mechanism SCRAM-SHA-256
      rpk topic create transactions --brokers redpanda.internal.net:29092 --user user --password redpanda --sasl-mechanism SCRAM-SHA-256
      rpk topic create balances -c cleanup.policy=compact --brokers redpanda.internal.net:29092 --user user --password redpanda --sasl-mechanism SCRAM-SHA-256
      rpk topic create payment-requests -c cleanup.policy=compact --brokers redpanda.internal.net:29092 --user user --password redpanda --sasl-mechanism SCRAM-SHA-256
      "
#  streampay-service:
#    image: "streampay-service:latest"
#    networks:
#      - net0
#    environment:
#      SPRING_KAFKA_APPLICATION_ID: stream-service
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka.internal.net:29092
#      CHAT_USERS_TOPIC: users
#      CHAT_CHANNELS_TOPIC: channels
#      CHAT_SUBSCRIPTIONS_TOPIC: subscriptions
#      CHAT_COMMANDS_TOPIC: commands
#      CHAT_MESSAGEs_TOPIC: messages
#
#  zilla:
#    image: "ghcr.io/aklivity/zilla:develop-SNAPSHOT"
#    hostname: "zilla"
#    command: [ "start", "-v", "-e"]
#    volumes:
#      - ./zilla.json:/zilla.json:ro
#    networks:
#      - net0
#    ports:
#      - "8080:8080"
#      - "9090:9090"

